global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'metabase'
    static_configs:
      - targets: ['metabase:3300']
  
  - job_name: 'jmx'
    static_configs:
      - targets: ['metabase:3301']
  
  - job_name: 'nginx-border'
    static_configs:
      - targets: ['nginx-border-exporter:9113']
  
  - job_name: 'nginx-internal'
    static_configs:
      - targets: ['nginx-internal-exporter:9113']
  
  - job_name: 'postgres-data1-exporter'
    static_configs:
      - targets: ['postgres-data1-exporter:9187']
  
  - job_name: 'postgres-app-db-exporter'
    static_configs:
      - targets: ['postgres-app-db-exporter:9187']
  
  - job_name: 'postgres-another-data-exporter'
    static_configs:
      - targets: ['postgres-another-data-exporter:9187']

  # - job_name: 'tempo'
  #   static_configs:
  #     - targets: [ 'tempo:3200' ]
  
  # - job_name: 'loki'
  #   static_configs:
  #     - targets: [ 'loki:3100' ]